input:
  http_server:
    address: ":8888"
    path: /telemetry
    allowed_verbs: [ GET, POST ]


pipeline:
  processors:
    # Inspect the incoming message and conditionally enrich
    - mapping: |
        root = this
        root.vehicle_alerts = []
        root.high_risk_behavior = []
        
        #root.event_datetime = timestamp_unix()

        if this.speed > 85 {
          root.high_risk_behavior = root.high_risk_behavior.append("SPEED")
        } 

        if this.airbag > 95 {
          root.vehicle_alerts = root.vehicle_alerts.append("AIRBAG")
        } 

        if this.low_tire_pressure_alert < 25 {
          root.vehicle_alerts = root.vehicle_alerts.append("LOW TIRE PRESSURE")
        } 

        if this.tail_light_alert > 75 {
          root.vehicle_alerts = root.vehicle_alerts.append("TAIL LIGHT OUT")
        }


buffer:
  memory:
    limit: 524288000 # 50MiB
    batch_policy:
      enabled: true
      count: 1000
      byte_size: 33554432 # 32MiB
      period: "3s"


output:
  switch:
      cases:
        - check: this.vehicle_alerts.length() > 0
          # If the vehicle_alerts array is populated, route to vehicle alert topic
          output:
            redpanda:
              seed_brokers: [ ${REDPANDA_BROKERS} ]
              topic: vehicle_alert
          continue: true

        - check: this.high_risk_behavior.length() > 0
          # If the risky behavior array is populated, route to risky behavior topic
          output:
            redpanda:
              seed_brokers: [ ${REDPANDA_BROKERS} ]
              topic: vehicle_high_risk_behavior
          continue: true

        - output:
            # send everything to the vehicle telemetry topic
            redpanda:
              seed_brokers: [ ${REDPANDA_BROKERS} ]
              topic: vehicle_telemetry

logger:
  level: DEBUG
  format: logfmt
  add_timestamp: true
  timestamp_name: ts
