input:
 generate:
   interval: 0.001s
   mapping: |
     root.msgid = uuid_v4()
     root.vehicle_id = nanoid(24)
     root.latitude = fake("latitude")
     root.longitude = fake("longitude")
     root.speed = random_int(seed:timestamp_unix_nano(), min:0, max:100)
     root.airbag = random_int(seed:timestamp_unix_nano(), min:0, max:100)
     root.low_tire_pressure_alert = random_int(seed:timestamp_unix_nano(), min:0, max:100)
     root.tail_light_alert = random_int(seed:timestamp_unix_nano(), min:0, max:100)
   #  root.event_datetime = timestamp_unix()

pipeline:
  processors:
    - log:
        level: INFO
        message: '${! content() }'

output:
  label: ""
  http_client:
    url: "http://localhost:8888/telemetry"
    verb: POST
    headers: {}
    rate_limit: "" # No default (optional)
    timeout: 5s
    max_in_flight: 64
